### ISSUE TITLE
Grafana Issue

### ISSUE THREAD

**Issue by ethanhunt4233** [bobrik/docker-collectd-mesos#1]
We are getting below error while integrating Grafana with these metrics.

```
TypeError: Cannot read property 'length' of undefined
at h.convertDataPointsToMs (http://host:8080/app/app.6e379bdb.js:31:22799)
at i (http://host:8080/app/app.6e379bdb.js:10:29774)
at http://host:8080/app/app.6e379bdb.js:10:29946
at l.$eval (http://host:8080/app/app.6e379bdb.js:12:5068)
at l.$digest (http://host:8080/app/app.6e379bdb.js:12:3586)
at l.$apply (http://host:8080/app/app.6e379bdb.js:12:5324)
at h (http://host:8080/app/app.6e379bdb.js:10:13582)
at q (http://host:8080/app/app.6e379bdb.js:10:15389)
at XMLHttpRequest.u.onload (http://host:8080/app/app.6e379bdb.js:10:15929)
```

**Comment by bobrik** [comment]
Please open issue for Grafana.
